### ISSUE TITLE
Column label re-order not changing cell contents properly

### ISSUE THREAD

**Issue by jcreel** [TexasDigitalLibrary/Vireo#720] opened 2018-02-08 21:50 UTC
When customizing the order of columns in List View  - the values in the columns do not always match the column header.  See attached example.   This seems to occur if the user is NOT starting the change from the Default column order.  If  you are starting from a saved view and change the columns, they are almost certainly jumbled. 
![_thumb_10503](https://user-images.githubusercontent.com/1204813/36000194-c665b090-0ce7-11e8-9b79-1a07de9593bc.png)

**Comment by wwelling** [comment] 2018-02-27 22:21
Resolved with previous issue. Unable to reproduce.

**Closed by wwelling** 2018-02-27 22:21 UTC
Labels: bug, in progress
