### ISSUE TITLE
Add Comment: public comment not possible without an email address

### ISSUE THREAD

**Issue by smutniak** [TexasDigitalLibrary/Vireo#1569] opened 2022-05-11 16:00 UTC
As Jon Crossno said:

I am experiencing a problem with adding a comment to the action log in a submission record in the admin view.

When I click on the Add Comment button, the intermodal appears with the Add Email Recipients checkbox already selected. When an email address is defined and text is entered in the subject and message body fields, the Comment button becomes available, which then saves the comment to the Action Log and send the email as expected.

However, I should be able to add a comment that is not associated with an email. When I deselect the Add Email Recipients checkbox and add the text to the subject and message body fields, the Comment button remains grayed out, which means that I am NOT able to add the comment. And this behavior is not what we want to happen.

**Comment by jcreel** [comment] 2023-03-09 22:02
What is the intended difference between public and private comments?  Can a comment be considered public without any associated emails?

**Comment by cstarcher** [comment] 2023-03-10 01:14
I've asked for clarification from Jon.

**Comment by jcross2562** [comment] 2023-03-10 14:54
I guess I'm confused. Why would you not want comments to be public? Everything that is posted to the Action Log automatically is made public, and those generally do not have any associated emails. Administrators should be able to do the same.

When I see "private" comments, I think they are only visible for me (or possibly other administrators). But the public comments should be visible to everyone, including the student if they ever need to login and see the status of their submission. And the public commenting should be the default -- with or without having to send an associated email.

In my specific case, I want to add a public comment when I make a change of some kind to the metadata that is different from what the student entered. (For example, the student may have selected the wrong embargo option, or the graduation semester date has changed a little from what was originally entered.) This behavior existed in Vireo 3, and I used it constantly. I've had to do a workaround in Vireo 4 of sending an email to myself, but that is an extra step that seems unnecessary.

Does this help? If not, let me know.

**Comment by cstarcher** [comment] 2023-03-10 18:54
Private comments are only visible to Reviewer, Manager, and Admin in the Action Log. It is also visible on the Faculty Review page.

Public comments are visible in the Action Log to the roles above. In addition, they are visible to students on the submission view page.

My recommendation is to remove the validation in the modal that requires emails to submit public comments. The emails should be optional.

**Comment by cstarcher** [comment] 2023-03-10 21:47
Need to check that there is no requirement on the back end for an email address.

**Comment by kaladay** [comment] 2023-03-14 19:15
@cstarcher
The Faculty Review page for a submission explicitly only shows public action logs (comments).
see: https://github.com/TexasDigitalLibrary/Vireo/blob/5f46663ddb63b20c89463cb6980f7575646e8923/src/main/webapp/app/views/submission/advisorReview.html#L16

I encountered the following bug and reported here:
- https://github.com/TexasDigitalLibrary/Vireo/issues/1608

This bug is relevant here as when you are testing public/private, you are going to see empty rows. These empty rows are, fyi, not a regression in any changes you may make while resolving this "making public comments without email address..." issue.

**Comment by kaladay** [comment] 2023-03-14 19:19
I also thing that this is a bug because the "Add Email Recipients" checkbox can be unclicked.
When unclicked the e-mail address goes away but the submit button is not clickable.
If the "Add Email Recipients" checkbox is not checked, then submission without any email should (or really, must) be allowed.

**Comment by cstarcher** [comment] 2023-03-21 22:42
Relates to #1296

**Closed** 2023-03-31 18:45 UTC
Labels: question
