### ISSUE TITLE
Authentication failed login 

### ISSUE THREAD

**Issue by get04** [TexasDigitalLibrary/Vireo#1410] opened 2019-11-27 12:50 UTC
Greetings, 
My Vireo is not letting to login.
I have different accounts generated via the system, i can see them in the PostgreSQL database.
but i could not login using any of the accounts with different roles, on login screen it says authentication failed!

**Comment by smutniak** [comment] 2020-02-11 15:19
Not reproducible in ubuntu 16.04 nor 18.04 - awaiting further info from the person I believe to be the original poster via other channels.

**Comment by smutniak** [comment] 2020-02-14 18:00
I have not received further information from the original poster.  Since this problem has not been evident in the cases highlighted above or elsewhere i will close this ticket.

**Closed by smutniak** 2020-02-14 18:00 UTC
Labels: 2PT
